In [3]:
from ScraperFC.fbref import FBref

fb = FBref()

data = fb.scrape_stats(
    year="2024-2025",
    league="England Premier League",
    stat_category="passing"
)

print(data.keys())

Running
dict_keys(['squad', 'opponent', 'player'])

In [11]:
player_df = data["player"]

print(player_df.shape)
print(player_df.columns.tolist())
player_df.head()

(596, 30)
[('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Nation'), ('Unnamed: 3_level_0', 'Pos'), ('Unnamed: 4_level_0', 'Squad'), ('Unnamed: 5_level_0', 'Age'), ('Unnamed: 6_level_0', 'Born'), ('Unnamed: 7_level_0', '90s'), ('Total', 'Cmp'), ('Total', 'Att'), ('Total', 'Cmp%'), ('Total', 'TotDist'), ('Total', 'PrgDist'), ('Short', 'Cmp'), ('Short', 'Att'), ('Short', 'Cmp%'), ('Medium', 'Cmp'), ('Medium', 'Att'), ('Medium', 'Cmp%'), ('Long', 'Cmp'), ('Long', 'Att'), ('Long', 'Cmp%'), ('Unnamed: 22_level_0', 'Ast'), ('Unnamed: 23_level_0', 'A-xAG'), ('Unnamed: 24_level_0', 'KP'), ('Unnamed: 25_level_0', '1/3'), ('Unnamed: 26_level_0', 'PPA'), ('Unnamed: 27_level_0', 'CrsPA'), ('Unnamed: 28_level_0', 'Matches'), ('Player ID', '')]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2  Joshua Acheampong            eng ENG                 DF
2                  3        Tyler Adams             us USA                 MF
3                  4   Tosin Adarabioyo            eng ENG                 DF
4                  5      Simon Adingra             ci CIV                 MF

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
               Squad                Age               Born                90s
0        Bournemouth                 24               2000                1.0
1            Chelsea                 18               2006                1.9
2        Bournemouth                 25               1999               21.8
3            Chelsea                 26               1997               15.7
4           Brighton                 22               2002               12.2

  Total       ... Long      Unnamed: 22_level_0 Unnamed: 23_level_0  \
    Cmp  Att  ...  Att Cmp%                 Ast               A-xAG
0   NaN  NaN  ...  NaN  NaN                   0                 NaN
1   NaN  NaN  ...  NaN  NaN                   0                 NaN
2   NaN  NaN  ...  NaN  NaN                   3                 NaN
3   NaN  NaN  ...  NaN  NaN                   1                 NaN
4   NaN  NaN  ...  NaN  NaN                   2                 NaN

  Unnamed: 24_level_0 Unnamed: 25_level_0 Unnamed: 26_level_0  \
                   KP                 1/3                 PPA
0                 NaN                 NaN                 NaN
1                 NaN                 NaN                 NaN
2                 NaN                 NaN                 NaN
3                 NaN                 NaN                 NaN
4                 NaN                 NaN                 NaN

  Unnamed: 27_level_0 Unnamed: 28_level_0 Player ID
                CrsPA             Matches
0                 NaN             Matches  774cf58b
1                 NaN             Matches  b7e62e1d
2                 NaN             Matches  2b09d998
3                 NaN             Matches  c81d773d
4                 NaN             Matches  4dcec659

[5 rows x 30 columns]

In [12]:
print(player_df.columns)

MultiIndex([( 'Unnamed: 0_level_0',      'Rk'),
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 2_level_0',  'Nation'),
            ( 'Unnamed: 3_level_0',     'Pos'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',     'Age'),
            ( 'Unnamed: 6_level_0',    'Born'),
            ( 'Unnamed: 7_level_0',     '90s'),
            (              'Total',     'Cmp'),
            (              'Total',     'Att'),
            (              'Total',    'Cmp%'),
            (              'Total', 'TotDist'),
            (              'Total', 'PrgDist'),
            (              'Short',     'Cmp'),
            (              'Short',     'Att'),
            (              'Short',    'Cmp%'),
            (             'Medium',     'Cmp'),
            (             'Medium',     'Att'),
            (             'Medium',    'Cmp%'),
            (               'Long',     'Cmp'),
            (               'Long',     'Att'),
            (               'Long',    'Cmp%'),
            ('Unnamed: 22_level_0',     'Ast'),
            ('Unnamed: 23_level_0',   'A-xAG'),
            ('Unnamed: 24_level_0',      'KP'),
            ('Unnamed: 25_level_0',     '1/3'),
            ('Unnamed: 26_level_0',     'PPA'),
            ('Unnamed: 27_level_0',   'CrsPA'),
            ('Unnamed: 28_level_0', 'Matches'),
            (          'Player ID',        '')],
           )

In [13]:
player_df.columns = [
    "_".join([str(x) for x in col if "Unnamed" not in str(x)])
    for col in player_df.columns
]

print(player_df.columns.tolist())

['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'Total_Cmp', 'Total_Att', 'Total_Cmp%', 'Total_TotDist', 'Total_PrgDist', 'Short_Cmp', 'Short_Att', 'Short_Cmp%', 'Medium_Cmp', 'Medium_Att', 'Medium_Cmp%', 'Long_Cmp', 'Long_Att', 'Long_Cmp%', 'Ast', 'A-xAG', 'KP', '1/3', 'PPA', 'CrsPA', 'Matches', 'Player ID_']

In [14]:
player_df.isna().sum()

Rk                 0
Player             0
Nation             1
Pos                0
Squad              0
Age                1
Born               1
90s                0
Total_Cmp        574
Total_Att        574
Total_Cmp%       574
Total_TotDist    574
Total_PrgDist    574
Short_Cmp        574
Short_Att        574
Short_Cmp%       574
Medium_Cmp       574
Medium_Att       574
Medium_Cmp%      574
Long_Cmp         574
Long_Att         574
Long_Cmp%        574
Ast                0
A-xAG            574
KP               574
1/3              574
PPA              574
CrsPA            574
Matches            0
Player ID_         0
dtype: int64

In [15]:
print(player_df.shape)

player_df.head()

(596, 30)

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Total_Cmp,Total_Att,...,Long_Att,Long_Cmp%,Ast,A-xAG,KP,1/3,PPA,CrsPA,Matches,Player ID_
0,1,Max Aarons,eng ENG,DF,Bournemouth,24,2000,1.0,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Matches,774cf58b
1,2,Joshua Acheampong,eng ENG,DF,Chelsea,18,2006,1.9,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Matches,b7e62e1d
2,3,Tyler Adams,us USA,MF,Bournemouth,25,1999,21.8,NaN,NaN,...,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,Matches,2b09d998
3,4,Tosin Adarabioyo,eng ENG,DF,Chelsea,26,1997,15.7,NaN,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,Matches,c81d773d
4,5,Simon Adingra,ci CIV,MF,Brighton,22,2002,12.2,NaN,NaN,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,Matches,4dcec659

In [16]:
data = fb.scrape_stats(
    year="2024-2025",
    league="England Premier League",
    stat_category="standard"
)

player_df = data["player"]

print(player_df.shape)
print(player_df.isna().sum().head(30))

(596, 26)
Unnamed: 0_level_0   Rk         0
Unnamed: 1_level_0   Player     0
Unnamed: 2_level_0   Nation     1
Unnamed: 3_level_0   Pos        0
Unnamed: 4_level_0   Squad      0
Unnamed: 5_level_0   Age        1
Unnamed: 6_level_0   Born       1
Playing Time         MP         0
                     Starts     0
                     Min        0
                     90s        0
Performance          Gls        0
                     Ast        0
                     G+A        0
                     G-PK       0
                     PK         0
                     PKatt      0
                     CrdY       0
                     CrdR       0
Per 90 Minutes       Gls        0
                     Ast        0
                     G+A        0
                     G-PK       0
                     G+A-PK     0
Unnamed: 24_level_0  Matches    0
Player ID                       0
dtype: int64

In [17]:
for cat in ["standard", "shooting", "passing","possesion"]:
    data = fb.scrape_stats(
        year="2024-2025",
        league="England Premier League",
        stat_category=cat
    )

    df = data["player"]

    print(cat)
    print(df.shape)
    print(df.isna().sum().sum())

standard
(596, 26)
3
shooting
(596, 20)
395
passing
(596, 30)
10909

ValueError: "possesion" is not a valid FBref stats category. Must be one of ['standard', 'goalkeeping', 'advanced goalkeeping', 'shooting', 'passing', 'pass types', 'goal and shot creation', 'defensive', 'possession', 'playing time', 'misc'].

In [18]:
for cat in ['pass types', 'goal and shot creation', 'defensive', 'possession', 'playing time', 'misc']:
    data = fb.scrape_stats(
        year="2024-2025",
        league="England Premier League",
        stat_category=cat
    )

    df = data["player"]

    print(cat)
    print(df.shape)
    print(df.isna().sum().sum())

pass types
(596, 25)
8039
goal and shot creation
(596, 26)
9187
defensive
(596, 26)
8039
An exception occurred Inspected target navigated or closed [code: -32000]
possession
(596, 30)
11483
playing time
(730, 26)
1709
misc
(596, 22)
1151

# Fbref No Longer Keeps Advanced Data of Passing, Defensive Actions etc #

# I will be reffering to Sofascore Now